In [6]:
from sportsdataverse.mbb import mbb_loaders
import pandas as pd

In [7]:
seasons = range(2004, 2026)
all_data = []

for season in seasons:
    try:
        data = mbb_loaders.load_mbb_team_boxscore(seasons=[season], return_as_pandas=True)
        all_data.append(data)
    except Exception as e:
        print(f"Error loading data for season {season}: {e}")

mbb_df = pd.concat(all_data, ignore_index=True)

mbb_df.head()

100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.12it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.36it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.00it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.96it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.35it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.08it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.13it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.40it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.98it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.36it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.72it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.71it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.67it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.69it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.38it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.51it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.25it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.51it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.48it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.28it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.67it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.03it/s]

,game_id,season,season_type,game_date,game_date_time,team_id,team_uid,team_slug,team_location,team_name,...,opponent_team_display_name,opponent_team_short_display_name,opponent_team_color,opponent_team_alternate_color,opponent_team_logo,opponent_team_score,largest_lead,fast_break_points,points_in_paint,turnover_points
0,233432507,2004,2,2003-12-09,2003-12-09 19:00:00-05:00,356,s:40~l:41~t:356,illinois-fighting-illini,Illinois,Fighting Illini,...,Providence Friars,Providence,000000,a3a19e,https://a.espncdn.com/i/teamlogos/ncaa/500/250...,70,<NA>,<NA>,<NA>,<NA>
1,233432507,2004,2,2003-12-09,2003-12-09 19:00:00-05:00,2507,s:40~l:41~t:2507,providence-friars,Providence,Friars,...,Illinois Fighting Illini,Illinois,ff5f05,13294b,https://a.espncdn.com/i/teamlogos/ncaa/500/356...,51,<NA>,<NA>,<NA>,<NA>
2,233300013,2004,2,2003-11-26,2003-11-26 22:00:00-05:00,38,s:40~l:41~t:38,colorado-buffaloes,Colorado,Buffaloes,...,Cal Poly Mustangs,Cal Poly,1E4D2B,eed897,https://a.espncdn.com/i/teamlogos/ncaa/500/13.png,62,<NA>,<NA>,<NA>,<NA>
3,233300013,2004,2,2003-11-26,2003-11-26 22:00:00-05:00,13,s:40~l:41~t:13,cal-poly-mustangs,Cal Poly,Mustangs,...,Colorado Buffaloes,Colorado,000000,cfb87c,https://a.espncdn.com/i/teamlogos/ncaa/500/38.png,73,<NA>,<NA>,<NA>,<NA>
4,233300356,2004,2,2003-11-26,2003-11-26 20:00:00-05:00,2382,s:40~l:41~t:2382,mercer-bears,Mercer,Bears,...,Illinois Fighting Illini,Illinois,ff5f05,13294b,https://a.espncdn.com/i/teamlogos/ncaa/500/356...,93,<NA>,<NA>,<NA>,<NA>

In [8]:
mbb_df.tail()

,game_id,season,season_type,game_date,game_date_time,team_id,team_uid,team_slug,team_location,team_name,...,opponent_team_display_name,opponent_team_short_display_name,opponent_team_color,opponent_team_alternate_color,opponent_team_logo,opponent_team_score,largest_lead,fast_break_points,points_in_paint,turnover_points
236509,401725796,2025,2,2024-11-04,2024-11-04 12:00:00-05:00,250,s:40~l:41~t:250,ut-arlington-mavericks,UT Arlington,Mavericks,...,UNT Dallas Trailblazers,UNT Dallas,<NA>,<NA>,<NA>,55,35,23,44,26
236510,401715872,2025,2,2024-11-04,2024-11-04 12:00:00-05:00,232,s:40~l:41~t:232,charleston-cougars,Charleston,Cougars,...,Southern Illinois Salukis,S Illinois,85283D,c2c3c0,https://a.espncdn.com/i/teamlogos/ncaa/500/79.png,80,12,0,40,8
236511,401715872,2025,2,2024-11-04,2024-11-04 12:00:00-05:00,79,s:40~l:41~t:79,southern-illinois-salukis,Southern Illinois,Salukis,...,Charleston Cougars,Charleston,7a2531,9e8959,https://a.espncdn.com/i/teamlogos/ncaa/500/232...,90,3,17,38,15
236512,401727499,2025,2,2024-11-04,2024-11-04 11:00:00-05:00,130262,s:40~l:41~t:130262,iu-columbus-crimson-pride,IU Columbus,Crimson Pride,...,IU Indianapolis Jaguars,IU Indy,A81F30,d59f0f,https://a.espncdn.com/i/teamlogos/ncaa/500/85.png,100,0,4,24,7
236513,401727499,2025,2,2024-11-04,2024-11-04 11:00:00-05:00,85,s:40~l:41~t:85,iu-indianapolis-jaguars,IU Indianapolis,Jaguars,...,IU Columbus Crimson Pride,IU Columbus,<NA>,<NA>,<NA>,44,58,11,48,25

In [9]:
mbb_df.columns

Index(['game_id', 'season', 'season_type', 'game_date', 'game_date_time',
       'team_id', 'team_uid', 'team_slug', 'team_location', 'team_name',
       'team_abbreviation', 'team_display_name', 'team_short_display_name',
       'team_color', 'team_alternate_color', 'team_logo', 'team_home_away',
       'team_score', 'team_winner', 'assists', 'blocks', 'defensive_rebounds',
       'field_goal_pct', 'field_goals_made', 'field_goals_attempted',
       'flagrant_fouls', 'fouls', 'free_throw_pct', 'free_throws_made',
       'free_throws_attempted', 'offensive_rebounds', 'steals',
       'team_turnovers', 'technical_fouls', 'three_point_field_goal_pct',
       'three_point_field_goals_made', 'three_point_field_goals_attempted',
       'total_rebounds', 'total_technical_fouls', 'total_turnovers',
       'turnovers', 'opponent_team_id', 'opponent_team_uid',
       'opponent_team_slug', 'opponent_team_location', 'opponent_team_name',
       'opponent_team_abbreviation', 'opponent_team_display_name',
       'opponent_team_short_display_name', 'opponent_team_color',
       'opponent_team_alternate_color', 'opponent_team_logo',
       'opponent_team_score', 'largest_lead', 'fast_break_points',
       'points_in_paint', 'turnover_points'],
      dtype='object')

In [10]:
columns_to_remove = [
    "team_uid", "team_color", "team_alternate_color", "team_logo", "opponent_team_uid", 
    "opponent_team_color", "opponent_team_alternate_color", "opponent_team_logo", "team_slug", 
    "team_name", "team_abbreviation", "team_display_name", "team_short_display_name", "opponent_team_slug", 
    "opponent_team_name", "opponent_team_abbreviation", "opponent_team_display_name", 
    "opponent_team_short_display_name", "opponent_team_id", "opponent_team_location", "opponent_team_score"]

mbb_df = mbb_df.drop(columns=columns_to_remove)

In [19]:
mbb_df

,game_id,season,season_type,game_date,game_date_time,team_id,team_location,team_home_away,team_score,team_winner,...,three_point_field_goals_made,three_point_field_goals_attempted,total_rebounds,total_technical_fouls,total_turnovers,turnovers,largest_lead,fast_break_points,points_in_paint,turnover_points
0,233432507,2004,2,2003-12-09,2003-12-09 19:00:00-05:00,356,Illinois,away,51,False,...,2,15,38,0,22,22,<NA>,<NA>,<NA>,<NA>
1,233432507,2004,2,2003-12-09,2003-12-09 19:00:00-05:00,2507,Providence,home,70,True,...,7,16,44,0,14,14,<NA>,<NA>,<NA>,<NA>
2,233300013,2004,2,2003-11-26,2003-11-26 22:00:00-05:00,38,Colorado,away,73,True,...,1,10,48,0,14,14,<NA>,<NA>,<NA>,<NA>
3,233300013,2004,2,2003-11-26,2003-11-26 22:00:00-05:00,13,Cal Poly,home,62,False,...,4,22,39,1,14,14,<NA>,<NA>,<NA>,<NA>
4,233300356,2004,2,2003-11-26,2003-11-26 20:00:00-05:00,2382,Mercer,away,61,False,...,7,21,30,0,21,21,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235857,401725796,2025,2,2024-11-04,2024-11-04 12:00:00-05:00,250,UT Arlington,home,90,True,...,9,26,45,0,14,14,35,23,44,26
235858,401715872,2025,2,2024-11-04,2024-11-04 12:00:00-05:00,232,Charleston,away,90,True,...,9,20,38,0,17,17,12,0,40,8
235859,401715872,2025,2,2024-11-04,2024-11-04 12:00:00-05:00,79,Southern Illinois,home,80,False,...,5,21,27,0,9,9,3,17,38,15
235860,401727499,2025,2,2024-11-04,2024-11-04 11:00:00-05:00,130262,IU Columbus,away,44,False,...,4,19,27,0,16,16,0,4,24,7
235861,401727499,2025,2,2024-11-04,2024-11-04 11:00:00-05:00,85,IU Indianapolis,home,100,True,...,12,31,64,0,5,5,58,11,48,25

In [15]:
def concatenate_team_stats(mbb_df):
    concatenated_df = mbb_df.merge(
        mbb_df, 
        on='game_id', 
        suffixes=('', '_opp')
    )
    concatenated_df = concatenated_df[
        concatenated_df['team_location'] != concatenated_df['team_location_opp']
    ]
    new_column_names = {
        col: col if '_opp' not in col else 'opp_' + col.replace('_opp', '')
        for col in concatenated_df.columns
    }
    concatenated_df.rename(columns=new_column_names, inplace=True)
    
    return concatenated_df

concatenated_stats = concatenate_team_stats(mbb_df)
concatenated_stats

,game_id,season,season_type,game_date,game_date_time,team_id,team_location,team_home_away,team_score,team_winner,...,opp_three_point_field_goals_made,opp_three_point_field_goals_attempted,opp_total_rebounds,opp_total_technical_fouls,opp_total_turnovers,opp_turnovers,opp_largest_lead,opp_fast_break_points,opp_points_in_paint,opp_turnover_points
1,233432507,2004,2,2003-12-09,2003-12-09 19:00:00-05:00,356,Illinois,away,51,False,...,7,16,44,0,14,14,<NA>,<NA>,<NA>,<NA>
2,233432507,2004,2,2003-12-09,2003-12-09 19:00:00-05:00,2507,Providence,home,70,True,...,2,15,38,0,22,22,<NA>,<NA>,<NA>,<NA>
5,233300013,2004,2,2003-11-26,2003-11-26 22:00:00-05:00,38,Colorado,away,73,True,...,4,22,39,1,14,14,<NA>,<NA>,<NA>,<NA>
6,233300013,2004,2,2003-11-26,2003-11-26 22:00:00-05:00,13,Cal Poly,home,62,False,...,1,10,48,0,14,14,<NA>,<NA>,<NA>,<NA>
9,233300356,2004,2,2003-11-26,2003-11-26 20:00:00-05:00,2382,Mercer,away,61,False,...,5,16,47,0,13,13,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
473018,401725796,2025,2,2024-11-04,2024-11-04 12:00:00-05:00,250,UT Arlington,home,90,True,...,5,14,45,0,21,21,0,9,24,10
473021,401715872,2025,2,2024-11-04,2024-11-04 12:00:00-05:00,232,Charleston,away,90,True,...,5,21,27,0,9,9,3,17,38,15
473022,401715872,2025,2,2024-11-04,2024-11-04 12:00:00-05:00,79,Southern Illinois,home,80,False,...,9,20,38,0,17,17,12,0,40,8
473025,401727499,2025,2,2024-11-04,2024-11-04 11:00:00-05:00,130262,IU Columbus,away,44,False,...,12,31,64,0,5,5,58,11,48,25
473026,401727499,2025,2,2024-11-04,2024-11-04 11:00:00-05:00,85,IU Indianapolis,home,100,True,...,4,19,27,0,16,16,0,4,24,7

In [19]:
concatenated_stats.columns

Index(['game_id', 'season', 'season_type', 'game_date', 'game_date_time',
       'team_id', 'team_location', 'team_home_away', 'team_score',
       'team_winner', 'assists', 'blocks', 'defensive_rebounds',
       'field_goal_pct', 'field_goals_made', 'field_goals_attempted',
       'flagrant_fouls', 'fouls', 'free_throw_pct', 'free_throws_made',
       'free_throws_attempted', 'offensive_rebounds', 'steals',
       'team_turnovers', 'technical_fouls', 'three_point_field_goal_pct',
       'three_point_field_goals_made', 'three_point_field_goals_attempted',
       'total_rebounds', 'total_technical_fouls', 'total_turnovers',
       'turnovers', 'largest_lead', 'fast_break_points', 'points_in_paint',
       'turnover_points', 'opp_season', 'opp_season_type', 'opp_game_date',
       'opp_game_date_time', 'opp_team_id', 'opp_team_location',
       'opp_team_home_away', 'opp_team_score', 'opp_team_winner',
       'opp_assists', 'opp_blocks', 'opp_defensive_rebounds',
       'opp_field_goal_pct', 'opp_field_goals_made',
       'opp_field_goals_attempted', 'opp_flagrant_fouls', 'opp_fouls',
       'opp_free_throw_pct', 'opp_free_throws_made',
       'opp_free_throws_attempted', 'opp_offensive_rebounds', 'opp_steals',
       'opp_team_turnovers', 'opp_technical_fouls',
       'opp_three_point_field_goal_pct', 'opp_three_point_field_goals_made',
       'opp_three_point_field_goals_attempted', 'opp_total_rebounds',
       'opp_total_technical_fouls', 'opp_total_turnovers', 'opp_turnovers',
       'opp_largest_lead', 'opp_fast_break_points', 'opp_points_in_paint',
       'opp_turnover_points'],
      dtype='object')

In [23]:
columns_to_remove = ['opp_season_type','opp_season','opp_game_date','opp_game_date_time',]

concatenated_stats = concatenated_stats.drop(columns=columns_to_remove)

In [25]:
concatenated_stats = concatenated_stats.sort_values("game_date")

In [26]:
concatenated_stats

,game_id,season,season_type,game_date,game_date_time,team_id,team_location,team_home_away,team_score,team_winner,...,opp_three_point_field_goals_made,opp_three_point_field_goals_attempted,opp_total_rebounds,opp_total_technical_fouls,opp_total_turnovers,opp_turnovers,opp_largest_lead,opp_fast_break_points,opp_points_in_paint,opp_turnover_points
45,233280269,2004,2,2003-11-24,2003-11-24 21:00:00-05:00,128,Northern Michigan,away,58,False,...,5,18,48,0,22,22,<NA>,<NA>,<NA>,<NA>
46,233280269,2004,2,2003-11-24,2003-11-24 21:00:00-05:00,269,Marquette,home,70,True,...,11,27,22,0,24,24,<NA>,<NA>,<NA>,<NA>
5,233300013,2004,2,2003-11-26,2003-11-26 22:00:00-05:00,38,Colorado,away,73,True,...,4,22,39,1,14,14,<NA>,<NA>,<NA>,<NA>
6,233300013,2004,2,2003-11-26,2003-11-26 22:00:00-05:00,13,Cal Poly,home,62,False,...,1,10,48,0,14,14,<NA>,<NA>,<NA>,<NA>
9,233300356,2004,2,2003-11-26,2003-11-26 20:00:00-05:00,2382,Mercer,away,61,False,...,5,16,47,0,13,13,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
451794,401721926,2025,2,2025-03-01,2025-03-01 12:00:00-05:00,2142,Colgate,home,59,False,...,12,26,28,0,13,13,14,7,24,12
451797,401719168,2025,2,2025-03-01,2025-03-01 12:00:00-05:00,41,UConn,away,75,True,...,8,20,27,0,7,7,4,5,22,6
451798,401719168,2025,2,2025-03-01,2025-03-01 12:00:00-05:00,2507,Providence,home,63,False,...,9,20,36,0,11,11,17,4,36,14
451801,401719167,2025,2,2025-03-01,2025-03-01 12:00:00-05:00,2086,Butler,away,70,False,...,12,28,36,0,6,6,15,9,32,5
451802,401719167,2025,2,2025-03-01,2025-03-01 12:00:00-05:00,222,Villanova,home,80,True,...,10,28,33,0,5,5,1,5,30,5

In [27]:
concatenated_stats = concatenated_stats.reset_index(drop=True)

In [30]:
def add_target(team_location):
    team_location["target"] = team_location["team_winner"].shift(-1)
    return team_location

concatenated_stats = concatenated_stats.groupby("team_location", group_keys=False).apply(add_target)

In [ ]:
concatenated_stats

In [33]:
concatenated_stats[concatenated_stats["team_location"] == "Providence"]

,game_id,season,season_type,game_date,game_date_time,team_id,team_location,team_home_away,team_score,team_winner,...,opp_three_point_field_goals_attempted,opp_total_rebounds,opp_total_technical_fouls,opp_total_turnovers,opp_turnovers,opp_largest_lead,opp_fast_break_points,opp_points_in_paint,opp_turnover_points,target
23,233432507,2004,2,2003-12-09,2003-12-09 19:00:00-05:00,2507,Providence,home,70,True,...,15,38,0,22,22,<NA>,<NA>,<NA>,<NA>,True
89,243212507,2005,2,2004-11-16,2004-11-16 19:00:00-05:00,2507,Providence,home,83,True,...,22,36,0,13,13,13,<NA>,<NA>,<NA>,True
121,243232507,2005,2,2004-11-18,2004-11-18 19:30:00-05:00,2507,Providence,home,89,True,...,20,32,0,14,14,0,<NA>,<NA>,<NA>,True
313,243252507,2005,2,2004-11-20,2004-11-20 19:30:00-05:00,2507,Providence,home,79,True,...,24,35,0,22,22,3,<NA>,<NA>,<NA>,False
709,243292507,2005,2,2004-11-24,2004-11-24 19:00:00-05:00,2507,Providence,home,67,False,...,15,45,0,16,16,18,<NA>,<NA>,<NA>,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234675,401719142,2025,2,2025-02-12,2025-02-12 20:00:00-05:00,2507,Providence,home,82,False,...,27,35,0,11,11,26,10,22,21,True
234949,401719144,2025,2,2025-02-15,2025-02-15 18:00:00-05:00,2507,Providence,home,75,True,...,19,30,0,9,9,0,0,18,7,False
235378,401719153,2025,2,2025-02-19,2025-02-19 19:00:00-05:00,2507,Providence,away,72,False,...,23,36,2,10,10,25,22,36,18,False
235956,401719159,2025,2,2025-02-25,2025-02-25 19:00:00-05:00,2507,Providence,away,52,False,...,41,39,0,10,10,31,16,18,19,False
236511,401719168,2025,2,2025-03-01,2025-03-01 12:00:00-05:00,2507,Providence,home,63,False,...,20,36,0,11,11,17,4,36,14,<NA>

In [45]:
concatenated_stats['target'] = concatenated_stats['target'].astype('float')
concatenated_stats["target"][pd.isnull(concatenated_stats["target"])] = 2
concatenated_stats["target"] = concatenated_stats["target"].astype(int, errors="ignore")

C:\Users\bianc\AppData\Local\Temp\ipykernel_6552\2272748221.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_stats["target"][pd.isnull(concatenated_stats["target"])] = 2

In [46]:
concatenated_stats

          game_id  season  season_type   game_date             game_date_time  team_id      team_location team_home_away  team_score team_winner  assists  blocks  defensive_rebounds  field_goal_pct  field_goals_made  field_goals_attempted  flagrant_fouls  fouls  free_throw_pct  free_throws_made  free_throws_attempted  offensive_rebounds  steals  team_turnovers  technical_fouls  three_point_field_goal_pct  three_point_field_goals_made  three_point_field_goals_attempted  total_rebounds  total_technical_fouls  total_turnovers  turnovers largest_lead fast_break_points points_in_paint turnover_points  opp_team_id    opp_team_location opp_team_home_away  opp_team_score opp_team_winner  opp_assists  opp_blocks  opp_defensive_rebounds  opp_field_goal_pct  opp_field_goals_made  opp_field_goals_attempted  opp_flagrant_fouls  opp_fouls  opp_free_throw_pct  opp_free_throws_made  opp_free_throws_attempted  opp_offensive_rebounds  opp_steals  opp_team_turnovers  opp_technical_fouls  opp_three_point_field_goal_pct  opp_three_point_field_goals_made  opp_three_point_field_goals_attempted  opp_total_rebounds  opp_total_technical_fouls  opp_total_turnovers  opp_turnovers opp_largest_lead opp_fast_break_points opp_points_in_paint opp_turnover_points  target
0       233280269    2004            2  2003-11-24  2003-11-24 21:00:00-05:00      128  Northern Michigan           away          58       False       20       3                  16            42.0                21                     50               0     25            50.0                 5                     10                   5      14               2                0                        40.7                            11                                 27              22                      0               24         24         <NA>              <NA>            <NA>            <NA>          269            Marquette               home              70            True           14           2                      27                44.1                    26                         59                   0         16                56.5                    13                         23                      19           7                   0                    0                            27.8                                 5                                     18                  48                          0                   22             22             <NA>                  <NA>                <NA>                <NA>       0
1       233280269    2004            2  2003-11-24  2003-11-24 21:00:00-05:00      269          Marquette           home          70        True       14       2                  27            44.1                26                     59               0     16            56.5                13                     23                  19       7               0                0                        27.8                             5                                 18              48                      0               22         22         <NA>              <NA>            <NA>            <NA>          128    Northern Michigan               away              58           False           20           3                      16                42.0                    21                         50                   0         25                50.0                     5                         10                       5          14                   2                    0                            40.7                                11                                     27                  22                          0                   24             24             <NA>                  <NA>                <NA>                <NA>       1
2       233300013    2004            2  2003-11-26  2003-11-26 22:00:00-05:00       38           Colorado           away          73        True        9       6                  33            44.4                28                     63               0     17            69.6                16                     23                  12       9               0                0                        10.0                             1                                 10              48                      0               14         14         <NA>              <NA>            <NA>            <NA>           13             Cal Poly               home              62           False           12           5                      26                36.1                    22                         61                   0         20                70.0                    14                         20                      10           8                   1                    1                            18.2                                 4                                     22                  39                          1                   14             14             <NA>                  <NA>                <NA>                <NA>       1
3       233300013    2004            2  2003-11-26  2003-11-26 22:00:00-05:00       13           Cal Poly           home          62       False       12       5                  26            36.1                22                     61               0     20            70.0                14                     20                  10       8               1                1                        18.2                             4                                 22              39                      1               14         14         <NA>              <NA>            <NA>            <NA>           38             Colorado               away              73            True            9           6                      33                44.4                    28                         63                   0         17                69.6                    16                         23                      12           9                   0                    0                            10.0                                 1                                     10                  48                          0                   14             14             <NA>                  <NA>                <NA>                <NA>       0
4       233300356    2004            2  2003-11-26  2003-11-26 20:00:00-05:00     2382             Mercer           away          61       False       12       5                  13            40.0                22                     55               0     15            58.8                10                     17                  14       3               0                0                        33.3                             7                                 21              30                      0               21         21         <NA>              <NA>            <NA>            <NA>          356             Illinois               home              93            True           17           3                      25                53.6                    37                         69                   0         19                82.4                    14                         17                      19           6                   0                    0                            31.3                                 5                                     16                  47                          0                   13             13             <NA>                  <NA>                <NA>                <NA>       0
...           ...     ...          ...         ...                        ...      ...                ...            ...         ...         ...      ...     ...                 ...             ...               ...                    ...             ...    ...             ...               ...                    ...                 ...     ...             ...              ...                         ...                           ...                                ...             ...                    ...              ...        ...          ...               ...             ...             ...          ...                  ...                ...             ...             ...          ...         ...                     ...                 ...                   ...                        ...                 ...        ...                 ...                   ...                        ...                     ...         ...                 ...                  ...                             ...                               ...                                    ...                 ...                        ...                  ...            ...              ...                   ...                 ...                 ...     ...
236509  401721926    2025            2  2025-03-01  2025-03-01 12:00:00-05:00     2142            Colgate           home          59       False       17       2                  22            45.1                23                     51               0     13            62.5                 5                      8                   5       6               0                0                        30.8                             8                                 26              27                      0               14         14            6                 4              20              10           44  American University               away              67            True           16           1                      24                49.0                    25                         51                   0         12                62.5                     5                          8                       4           8                   1                    0                            46.2                                12                                     26                  28                          0                   13             13               14                     7                  24                  12       2
236510  401719168    2025            2  2025-03-01  2025-03-01 12:00:00-05:00       41              UConn           away          75        True       14       7                  27            53.8                28                     52               0     15            66.7                10                     15                   9       3               0                0                        45.0                             9                                 20              36                      0               11         11           17                 4              36              14         2507           Providence               home              63           False           13           2                      19                40.0                    20                         50                   0         16                65.2                    15                         23                       8           7                   0                    0                            40.0                                 8                                     20                  27                          0                    7              7                4                     5                  22                   6       2
236511  401719168    2025            2  2025-03-01  2025-03-01 12:00:00-05:00     2507         Providence           home          63       False       13       2                  19            40.0                20                     50               0     16            65.2                15                     23                   8       7               0                0                        40.0                             8                                 20              27                      0                7          7            4                 5              22               6           41                UConn               away              75            True           14           7                      27                53.8                    28                         52                   0         15                66.7                    10                         15                       9           3                   0                    0                            45.0                                 9                                     20                  36                          0                   11             11               17                     4                  36                  14       2
236512  401719167    2025            2  2025-03-01  2025-03-01 12:00:00-05:00     2086             Butler           away          70       False       11       4                  24            40.0                26                     65               0     15            88.9                 8                      9                   9       2               0                0                        35.7                            10                                 28              33                      0                5          5            1                 5              30               5          222            Villanova               home              80            True           17           4                      31                50.8                    30                         59                   0         12                88.9                     8                          9                       5           3                   0                    0                            42.9                                12                                     28                  36                          0                    6              6               15                     9                  32                   5       2
236513  401719167    2025            2  2025-03-01  2025-03-01 12:00:00-05:00      222          Villanova           home          80        True       17       4                  31            50.8                30                     59               0     12            88.9                 8                      9                   5       3               0                0                        42.9                            12                                 28              36                      0                6          6           15                 9              32               5         2086               Butler               away              70           False           11           4                      24                40.0                    26                         65                   0         15                88.9                     8                          9                       9           2                   0                    0                            35.7                                10                                     28                  33                          0                    5              5                1                     5                  30                   5       2

[236514 rows x 68 columns]

In [49]:
concatenated_stats["team_winner"].value_counts()

team_winner
False    118257
True     118257
Name: count, dtype: int64[pyarrow]

In [50]:
concatenated_stats["target"].value_counts()

target
1    118054
0    116909
2      1551
Name: count, dtype: int64

In [51]:
nulls = pd.isnull(concatenated_stats).sum()

In [52]:
nulls = nulls[nulls > 0]

In [53]:
valid_columns = concatenated_stats.columns[~concatenated_stats.columns.isin(nulls.index)]

In [54]:
valid_columns

Index(['game_id', 'season', 'season_type', 'game_date', 'game_date_time',
       'team_id', 'team_location', 'team_home_away', 'team_score',
       'team_winner', 'assists', 'blocks', 'defensive_rebounds',
       'field_goal_pct', 'field_goals_made', 'field_goals_attempted',
       'flagrant_fouls', 'fouls', 'free_throw_pct', 'free_throws_made',
       'free_throws_attempted', 'offensive_rebounds', 'steals',
       'team_turnovers', 'technical_fouls', 'three_point_field_goal_pct',
       'three_point_field_goals_made', 'three_point_field_goals_attempted',
       'total_rebounds', 'total_technical_fouls', 'total_turnovers',
       'turnovers', 'opp_team_id', 'opp_team_location', 'opp_team_home_away',
       'opp_team_score', 'opp_team_winner', 'opp_assists', 'opp_blocks',
       'opp_defensive_rebounds', 'opp_field_goal_pct', 'opp_field_goals_made',
       'opp_field_goals_attempted', 'opp_flagrant_fouls', 'opp_fouls',
       'opp_free_throw_pct', 'opp_free_throws_made',
       'opp_free_throws_attempted', 'opp_offensive_rebounds', 'opp_steals',
       'opp_team_turnovers', 'opp_technical_fouls',
       'opp_three_point_field_goal_pct', 'opp_three_point_field_goals_made',
       'opp_three_point_field_goals_attempted', 'opp_total_rebounds',
       'opp_total_technical_fouls', 'opp_total_turnovers', 'opp_turnovers',
       'target'],
      dtype='object')

In [55]:
concatenated_stats = concatenated_stats[valid_columns].copy()

In [56]:
concatenated_stats

          game_id  season  season_type   game_date             game_date_time  team_id      team_location team_home_away  team_score team_winner  assists  blocks  defensive_rebounds  field_goal_pct  field_goals_made  field_goals_attempted  flagrant_fouls  fouls  free_throw_pct  free_throws_made  free_throws_attempted  offensive_rebounds  steals  team_turnovers  technical_fouls  three_point_field_goal_pct  three_point_field_goals_made  three_point_field_goals_attempted  total_rebounds  total_technical_fouls  total_turnovers  turnovers  opp_team_id    opp_team_location opp_team_home_away  opp_team_score opp_team_winner  opp_assists  opp_blocks  opp_defensive_rebounds  opp_field_goal_pct  opp_field_goals_made  opp_field_goals_attempted  opp_flagrant_fouls  opp_fouls  opp_free_throw_pct  opp_free_throws_made  opp_free_throws_attempted  opp_offensive_rebounds  opp_steals  opp_team_turnovers  opp_technical_fouls  opp_three_point_field_goal_pct  opp_three_point_field_goals_made  opp_three_point_field_goals_attempted  opp_total_rebounds  opp_total_technical_fouls  opp_total_turnovers  opp_turnovers  target
0       233280269    2004            2  2003-11-24  2003-11-24 21:00:00-05:00      128  Northern Michigan           away          58       False       20       3                  16            42.0                21                     50               0     25            50.0                 5                     10                   5      14               2                0                        40.7                            11                                 27              22                      0               24         24          269            Marquette               home              70            True           14           2                      27                44.1                    26                         59                   0         16                56.5                    13                         23                      19           7                   0                    0                            27.8                                 5                                     18                  48                          0                   22             22       0
1       233280269    2004            2  2003-11-24  2003-11-24 21:00:00-05:00      269          Marquette           home          70        True       14       2                  27            44.1                26                     59               0     16            56.5                13                     23                  19       7               0                0                        27.8                             5                                 18              48                      0               22         22          128    Northern Michigan               away              58           False           20           3                      16                42.0                    21                         50                   0         25                50.0                     5                         10                       5          14                   2                    0                            40.7                                11                                     27                  22                          0                   24             24       1
2       233300013    2004            2  2003-11-26  2003-11-26 22:00:00-05:00       38           Colorado           away          73        True        9       6                  33            44.4                28                     63               0     17            69.6                16                     23                  12       9               0                0                        10.0                             1                                 10              48                      0               14         14           13             Cal Poly               home              62           False           12           5                      26                36.1                    22                         61                   0         20                70.0                    14                         20                      10           8                   1                    1                            18.2                                 4                                     22                  39                          1                   14             14       1
3       233300013    2004            2  2003-11-26  2003-11-26 22:00:00-05:00       13           Cal Poly           home          62       False       12       5                  26            36.1                22                     61               0     20            70.0                14                     20                  10       8               1                1                        18.2                             4                                 22              39                      1               14         14           38             Colorado               away              73            True            9           6                      33                44.4                    28                         63                   0         17                69.6                    16                         23                      12           9                   0                    0                            10.0                                 1                                     10                  48                          0                   14             14       0
4       233300356    2004            2  2003-11-26  2003-11-26 20:00:00-05:00     2382             Mercer           away          61       False       12       5                  13            40.0                22                     55               0     15            58.8                10                     17                  14       3               0                0                        33.3                             7                                 21              30                      0               21         21          356             Illinois               home              93            True           17           3                      25                53.6                    37                         69                   0         19                82.4                    14                         17                      19           6                   0                    0                            31.3                                 5                                     16                  47                          0                   13             13       0
...           ...     ...          ...         ...                        ...      ...                ...            ...         ...         ...      ...     ...                 ...             ...               ...                    ...             ...    ...             ...               ...                    ...                 ...     ...             ...              ...                         ...                           ...                                ...             ...                    ...              ...        ...          ...                  ...                ...             ...             ...          ...         ...                     ...                 ...                   ...                        ...                 ...        ...                 ...                   ...                        ...                     ...         ...                 ...                  ...                             ...                               ...                                    ...                 ...                        ...                  ...            ...     ...
236509  401721926    2025            2  2025-03-01  2025-03-01 12:00:00-05:00     2142            Colgate           home          59       False       17       2                  22            45.1                23                     51               0     13            62.5                 5                      8                   5       6               0                0                        30.8                             8                                 26              27                      0               14         14           44  American University               away              67            True           16           1                      24                49.0                    25                         51                   0         12                62.5                     5                          8                       4           8                   1                    0                            46.2                                12                                     26                  28                          0                   13             13       2
236510  401719168    2025            2  2025-03-01  2025-03-01 12:00:00-05:00       41              UConn           away          75        True       14       7                  27            53.8                28                     52               0     15            66.7                10                     15                   9       3               0                0                        45.0                             9                                 20              36                      0               11         11         2507           Providence               home              63           False           13           2                      19                40.0                    20                         50                   0         16                65.2                    15                         23                       8           7                   0                    0                            40.0                                 8                                     20                  27                          0                    7              7       2
236511  401719168    2025            2  2025-03-01  2025-03-01 12:00:00-05:00     2507         Providence           home          63       False       13       2                  19            40.0                20                     50               0     16            65.2                15                     23                   8       7               0                0                        40.0                             8                                 20              27                      0                7          7           41                UConn               away              75            True           14           7                      27                53.8                    28                         52                   0         15                66.7                    10                         15                       9           3                   0                    0                            45.0                                 9                                     20                  36                          0                   11             11       2
236512  401719167    2025            2  2025-03-01  2025-03-01 12:00:00-05:00     2086             Butler           away          70       False       11       4                  24            40.0                26                     65               0     15            88.9                 8                      9                   9       2               0                0                        35.7                            10                                 28              33                      0                5          5          222            Villanova               home              80            True           17           4                      31                50.8                    30                         59                   0         12                88.9                     8                          9                       5           3                   0                    0                            42.9                                12                                     28                  36                          0                    6              6       2
236513  401719167    2025            2  2025-03-01  2025-03-01 12:00:00-05:00      222          Villanova           home          80        True       17       4                  31            50.8                30                     59               0     12            88.9                 8                      9                   5       3               0                0                        42.9                            12                                 28              36                      0                6          6         2086               Butler               away              70           False           11           4                      24                40.0                    26                         65                   0         15                88.9                     8                          9                       9           2                   0                    0                            35.7                                10                                     28                  33                          0                    5              5       2

[236514 rows x 60 columns]

In [57]:
df = concatenated_stats

In [80]:
from sklearn.linear_model import RidgeClassifier
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.model_selection import TimeSeriesSplit

rr = RidgeClassifier(alpha=1)

split = TimeSeriesSplit(n_splits=3)

sfs = SequentialFeatureSelector(rr, 
                                n_features_to_select=40, 
                                direction="forward",
                                cv=split,
                                n_jobs=1
                               )

In [81]:
df.columns

Index(['game_id', 'season', 'season_type', 'game_date', 'game_date_time',
       'team_id', 'team_location', 'team_home_away', 'team_score',
       'team_winner', 'assists', 'blocks', 'defensive_rebounds',
       'field_goal_pct', 'field_goals_made', 'field_goals_attempted',
       'flagrant_fouls', 'fouls', 'free_throw_pct', 'free_throws_made',
       'free_throws_attempted', 'offensive_rebounds', 'steals',
       'team_turnovers', 'technical_fouls', 'three_point_field_goal_pct',
       'three_point_field_goals_made', 'three_point_field_goals_attempted',
       'total_rebounds', 'total_technical_fouls', 'total_turnovers',
       'turnovers', 'opp_team_id', 'opp_team_location', 'opp_team_home_away',
       'opp_team_score', 'opp_team_winner', 'opp_assists', 'opp_blocks',
       'opp_defensive_rebounds', 'opp_field_goal_pct', 'opp_field_goals_made',
       'opp_field_goals_attempted', 'opp_flagrant_fouls', 'opp_fouls',
       'opp_free_throw_pct', 'opp_free_throws_made',
       'opp_free_throws_attempted', 'opp_offensive_rebounds', 'opp_steals',
       'opp_team_turnovers', 'opp_technical_fouls',
       'opp_three_point_field_goal_pct', 'opp_three_point_field_goals_made',
       'opp_three_point_field_goals_attempted', 'opp_total_rebounds',
       'opp_total_technical_fouls', 'opp_total_turnovers', 'opp_turnovers',
       'target'],
      dtype='object')

In [82]:
removed_columns = ['game_id', 'season', 'season_type', 'game_date', 'game_date_time',
       'team_id', 'team_location', 'team_home_away', 'opp_team_id', 'opp_team_location', 'opp_team_home_away','team_winner','opp_team_winner', "target"]
selected_columns = df.columns[~df.columns.isin(removed_columns)]

In [83]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[selected_columns] = scaler.fit_transform(df[selected_columns])

In [84]:
df

          game_id  season  season_type   game_date             game_date_time  team_id      team_location team_home_away  team_score team_winner   assists    blocks  defensive_rebounds  field_goal_pct  field_goals_made  field_goals_attempted  flagrant_fouls     fouls  free_throw_pct  free_throws_made  free_throws_attempted  offensive_rebounds    steals  team_turnovers  technical_fouls  three_point_field_goal_pct  three_point_field_goals_made  three_point_field_goals_attempted  total_rebounds  total_technical_fouls  total_turnovers  turnovers  opp_team_id    opp_team_location opp_team_home_away  opp_team_score opp_team_winner  opp_assists  opp_blocks  opp_defensive_rebounds  opp_field_goal_pct  opp_field_goals_made  opp_field_goals_attempted  opp_flagrant_fouls  opp_fouls  opp_free_throw_pct  opp_free_throws_made  opp_free_throws_attempted  opp_offensive_rebounds  opp_steals  opp_team_turnovers  opp_technical_fouls  opp_three_point_field_goal_pct  opp_three_point_field_goals_made  opp_three_point_field_goals_attempted  opp_total_rebounds  opp_total_technical_fouls  opp_total_turnovers  opp_turnovers  target
0       233280269    2004            2  2003-11-24  2003-11-24 21:00:00-05:00      128  Northern Michigan           away    0.278788       False  0.350877  0.142857            0.253968        0.498221          0.272727                  0.400             0.0  0.423729           0.500          0.092593               0.128205            0.098039  0.378378        0.066667         0.000000                       0.407                      0.366667                           0.341772        0.261905               0.000000         0.489796   0.489796          269            Marquette               home        0.351515            True     0.245614    0.095238                0.428571            0.523132              0.337662                      0.472                 0.0   0.271186               0.565              0.240741                   0.294872                0.372549    0.189189            0.000000             0.000000                           0.278                          0.166667                               0.227848            0.571429                   0.000000             0.448980       0.448980       0
1       233280269    2004            2  2003-11-24  2003-11-24 21:00:00-05:00      269          Marquette           home    0.351515        True  0.245614  0.095238            0.428571        0.523132          0.337662                  0.472             0.0  0.271186           0.565          0.240741               0.294872            0.372549  0.189189        0.000000         0.000000                       0.278                      0.166667                           0.227848        0.571429               0.000000         0.448980   0.448980          128    Northern Michigan               away        0.278788           False     0.350877    0.142857                0.253968            0.498221              0.272727                      0.400                 0.0   0.423729               0.500              0.092593                   0.128205                0.098039    0.378378            0.066667             0.000000                           0.407                          0.366667                               0.341772            0.261905                   0.000000             0.489796       0.489796       1
2       233300013    2004            2  2003-11-26  2003-11-26 22:00:00-05:00       38           Colorado           away    0.369697        True  0.157895  0.285714            0.523810        0.526690          0.363636                  0.504             0.0  0.288136           0.696          0.296296               0.294872            0.235294  0.243243        0.000000         0.000000                       0.100                      0.033333                           0.126582        0.571429               0.000000         0.285714   0.285714           13             Cal Poly               home        0.303030           False     0.210526    0.238095                0.412698            0.428233              0.285714                      0.488                 0.0   0.338983               0.700              0.259259                   0.256410                0.196078    0.216216            0.033333             0.071429                           0.182                          0.133333                               0.278481            0.464286                   0.071429             0.285714       0.285714       1
3       233300013    2004            2  2003-11-26  2003-11-26 22:00:00-05:00       13           Cal Poly           home    0.303030       False  0.210526  0.238095            0.412698        0.428233          0.285714                  0.488             0.0  0.338983           0.700          0.259259               0.256410            0.196078  0.216216        0.033333         0.071429                       0.182                      0.133333                           0.278481        0.464286               0.071429         0.285714   0.285714           38             Colorado               away        0.369697            True     0.157895    0.285714                0.523810            0.526690              0.363636                      0.504                 0.0   0.288136               0.696              0.296296                   0.294872                0.235294    0.243243            0.000000             0.000000                           0.100                          0.033333                               0.126582            0.571429                   0.000000             0.285714       0.285714       0
4       233300356    2004            2  2003-11-26  2003-11-26 20:00:00-05:00     2382             Mercer           away    0.296970       False  0.210526  0.238095            0.206349        0.474496          0.285714                  0.440             0.0  0.254237           0.588          0.185185               0.217949            0.274510  0.081081        0.000000         0.000000                       0.333                      0.233333                           0.265823        0.357143               0.000000         0.428571   0.428571          356             Illinois               home        0.490909            True     0.298246    0.142857                0.396825            0.635824              0.480519                      0.552                 0.0   0.322034               0.824              0.259259                   0.217949                0.372549    0.162162            0.000000             0.000000                           0.313                          0.166667                               0.202532            0.559524                   0.000000             0.265306       0.265306       0
...           ...     ...          ...         ...                        ...      ...                ...            ...         ...         ...       ...       ...                 ...             ...               ...                    ...             ...       ...             ...               ...                    ...                 ...       ...             ...              ...                         ...                           ...                                ...             ...                    ...              ...        ...          ...                  ...                ...             ...             ...          ...         ...                     ...                 ...                   ...                        ...                 ...        ...                 ...                   ...                        ...                     ...         ...                 ...                  ...                             ...                               ...                                    ...                 ...                        ...                  ...            ...     ...
236509  401721926    2025            2  2025-03-01  2025-03-01 12:00:00-05:00     2142            Colgate           home    0.284848       False  0.298246  0.095238            0.349206        0.534994          0.298701                  0.408             0.0  0.220339           0.625          0.092593               0.102564            0.098039  0.162162        0.000000         0.000000                       0.308                      0.266667                           0.329114        0.321429               0.000000         0.285714   0.285714           44  American University               away        0.333333            True     0.280702    0.047619                0.380952            0.581257              0.324675                      0.408                 0.0   0.203390               0.625              0.092593                   0.102564                0.078431    0.216216            0.033333             0.000000                           0.462                          0.400000                               0.329114            0.333333                   0.000000             0.265306       0.265306       2
236510  401719168    2025            2  2025-03-01  2025-03-01 12:00:00-05:00       41              UConn           away    0.381818        True  0.245614  0.333333            0.428571        0.638197          0.363636                  0.416             0.0  0.254237           0.667          0.185185               0.192308            0.176471  0.081081        0.000000         0.000000                       0.450                      0.300000                           0.253165        0.428571               0.000000         0.224490   0.224490         2507           Providence               home        0.309091           False     0.228070    0.095238                0.301587            0.474496              0.259740                      0.400                 0.0   0.271186               0.652              0.277778                   0.294872                0.156863    0.189189            0.000000             0.000000                           0.400                          0.266667                               0.253165            0.321429                   0.000000             0.142857       0.142857       2
236511  401719168    2025            2  2025-03-01  2025-03-01 12:00:00-05:00     2507         Providence           home    0.309091       False  0.228070  0.095238            0.301587        0.474496          0.259740                  0.400             0.0  0.271186           0.652          0.277778               0.294872            0.156863  0.189189        0.000000         0.000000                       0.400                      0.266667                           0.253165        0.321429               0.000000         0.142857   0.142857           41                UConn               away        0.381818            True     0.245614    0.333333                0.428571            0.638197              0.363636                      0.416                 0.0   0.254237               0.667              0.185185                   0.192308                0.176471    0.081081            0.000000             0.000000                           0.450                          0.300000                               0.253165            0.428571                   0.000000             0.224490       0.224490       2
236512  401719167    2025            2  2025-03-01  2025-03-01 12:00:00-05:00     2086             Butler           away    0.351515       False  0.192982  0.190476            0.380952        0.474496          0.337662                  0.520             0.0  0.254237           0.889          0.148148               0.115385            0.176471  0.054054        0.000000         0.000000                       0.357                      0.333333                           0.354430        0.392857               0.000000         0.102041   0.102041          222            Villanova               home        0.412121            True     0.298246    0.190476                0.492063            0.602610              0.389610                      0.472                 0.0   0.203390               0.889              0.148148                   0.115385                0.098039    0.081081            0.000000             0.000000                           0.429                          0.400000                               0.354430            0.428571                   0.000000             0.122449       0.122449       2
236513  401719167    2025            2  2025-03-01  2025-03-01 12:00:00-05:00      222          Villanova           home    0.412121        True  0.298246  0.190476            0.492063        0.602610          0.389610                  0.472             0.0  0.203390           0.889          0.148148               0.115385            0.098039  0.081081        0.000000         0.000000                       0.429                      0.400000                           0.354430        0.428571               0.000000         0.122449   0.122449         2086               Butler               away        0.351515           False     0.192982    0.190476                0.380952            0.474496              0.337662                      0.520                 0.0   0.254237               0.889              0.148148                   0.115385                0.176471    0.054054            0.000000             0.000000                           0.357                          0.333333                               0.354430            0.392857                   0.000000             0.102041       0.102041       2

[236514 rows x 60 columns]

In [85]:
sfs.fit(df[selected_columns], df["target"])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=40, n_jobs=1)

In [86]:
predictors = list(selected_columns[sfs.get_support()])

In [87]:
predictors

['team_score',
 'assists',
 'blocks',
 'field_goal_pct',
 'field_goals_made',
 'flagrant_fouls',
 'fouls',
 'free_throw_pct',
 'free_throws_made',
 'free_throws_attempted',
 'offensive_rebounds',
 'steals',
 'technical_fouls',
 'three_point_field_goal_pct',
 'three_point_field_goals_made',
 'three_point_field_goals_attempted',
 'total_rebounds',
 'total_technical_fouls',
 'total_turnovers',
 'turnovers',
 'opp_team_score',
 'opp_assists',
 'opp_blocks',
 'opp_field_goal_pct',
 'opp_field_goals_made',
 'opp_flagrant_fouls',
 'opp_fouls',
 'opp_free_throws_made',
 'opp_free_throws_attempted',
 'opp_offensive_rebounds',
 'opp_steals',
 'opp_team_turnovers',
 'opp_technical_fouls',
 'opp_three_point_field_goal_pct',
 'opp_three_point_field_goals_made',
 'opp_three_point_field_goals_attempted',
 'opp_total_rebounds',
 'opp_total_technical_fouls',
 'opp_total_turnovers',
 'opp_turnovers']

In [88]:
def backtest(data, model, predictors, start=2, step=1):
    all_predictions = []
    
    seasons = sorted(data["season"].unique())
    
    for i in range(start, len(seasons), step):
        season = seasons[i]
        train = data[data["season"] < season]
        test = data[data["season"] == season]
        
        model.fit(train[predictors], train["target"])
        
        preds = model.predict(test[predictors])
        preds = pd.Series(preds, index=test.index)
        combined = pd.concat([test["target"], preds], axis=1)
        combined.columns = ["actual", "prediction"]
        
        all_predictions.append(combined)
    return pd.concat(all_predictions)

In [89]:
predictions = backtest(df, rr, predictors)

In [90]:
from sklearn.metrics import accuracy_score
predictions = predictions[predictions["actual"] != 2]
accuracy_score(predictions["actual"], predictions["prediction"])

0.5698876722381119